[package]
name = "rs-battle-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
rand = "0.8.5"
unicode-segmentation = "1.11.0"
rusty_audio = "1.4.1"
